import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('side_hustles').del();

  await knex('side_hustles').insert([
    {
      title: 'Food Delivery Driver',
      company: 'DoorDash',
      description: 'Deliver food to customers in your area. Set your own hours and work when you want. Must have a valid drivers license and reliable vehicle.',
      category: 'gig',
      pay_range: '$15-25/hr',
      location: 'Nationwide',
      url: 'https://example.com/doordash',
      is_active: true,
    },
    {
      title: 'Freelance Graphic Designer',
      company: 'Fiverr',
      description: 'Create logos, social media graphics, and brand materials for clients worldwide. Work from anywhere on your own schedule.',
      category: 'freelance',
      pay_range: '$20-75/hr',
      location: 'Remote',
      url: 'https://example.com/fiverr',
      is_active: true,
    },
    {
      title: 'Virtual Assistant',
      company: 'Belay',
      description: 'Provide administrative support to businesses remotely. Tasks include email management, scheduling, and data entry.',
      category: 'remote',
      pay_range: '$18-30/hr',
      location: 'Remote',
      url: 'https://example.com/belay',
      is_active: true,
    },
    {
      title: 'Retail Holiday Associate',
      company: 'Target',
      description: 'Help with the holiday rush! Stock shelves, assist customers, and manage checkout. Flexible scheduling available.',
      category: 'seasonal',
      pay_range: '$15-18/hr',
      location: 'Multiple Locations',
      url: 'https://example.com/target',
      is_active: true,
    },
    {
      title: 'Tutoring - Math & Science',
      company: 'Wyzant',
      description: 'Tutor students in math and science subjects. Choose your own rates and availability. Teaching experience preferred.',
      category: 'freelance',
      pay_range: '$25-60/hr',
      location: 'Remote / In-person',
      url: 'https://example.com/wyzant',
      is_active: true,
    },
    {
      title: 'Warehouse Associate',
      company: 'Amazon',
      description: 'Pick, pack, and ship orders in a fulfillment center. Multiple shift options available. No experience necessary.',
      category: 'part_time',
      pay_range: '$16-22/hr',
      location: 'Multiple Locations',
      url: 'https://example.com/amazon',
      is_active: true,
    },
    {
      title: 'Rideshare Driver',
      company: 'Lyft',
      description: 'Drive passengers around your city. Earn money on your own schedule. Must pass a background check and have a clean driving record.',
      category: 'gig',
      pay_range: '$18-35/hr',
      location: 'Nationwide',
      url: 'https://example.com/lyft',
      is_active: true,
    },
    {
      title: 'Content Writer',
      company: 'Contently',
      description: 'Write blog posts, articles, and marketing copy for brands. Choose topics that interest you and set your own rates.',
      category: 'freelance',
      pay_range: '$0.10-1.00/word',
      location: 'Remote',
      url: 'https://example.com/contently',
      is_active: true,
    },
    {
      title: 'Dog Walker / Pet Sitter',
      company: 'Rover',
      description: 'Walk dogs, pet sit, and provide pet care services in your neighborhood. Great for animal lovers!',
      category: 'gig',
      pay_range: '$15-30/walk',
      location: 'Local',
      url: 'https://example.com/rover',
      is_active: true,
    },
    {
      title: 'Survey Taker',
      company: 'Swagbucks',
      description: 'Complete online surveys and earn rewards. Easy to do in your spare time from your phone or computer.',
      category: 'remote',
      pay_range: '$5-15/hr',
      location: 'Remote',
      url: 'https://example.com/swagbucks',
      is_active: true,
    },
  ]);
}
